default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapp_development
  username: blogapp
  password: gjjkulu
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: BlogApp_test

production:
  <<: *default
  database: BlogApp_production
  username: BlogApp
  password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %>
